apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
      - image: okteto.dev/busy:latest
        name: busy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "moviesjoy.to"
        - name: Vless_UUID
          value: "84125466-efb7-4cc4-9bb1-fa05d21a469a"
        - name: Vless_Path
          value: "/s236"
        - name: Vmess_UUID
          value: "84125466-efb7-4cc4-9bb1-fa05d21a469a"
        - name: Vmess_Path
          value: "/s248"
        - name: Share_Path
          value: "/share236"
